USE [master]
GO
/****** Object:  Database [investorfunds]    Script Date: 26-01-2025 23:58:30 ******/
CREATE DATABASE [investorfunds]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'investorfunds', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\investorfunds.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'investorfunds_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\investorfunds_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [investorfunds] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [investorfunds].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [investorfunds] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [investorfunds] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [investorfunds] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [investorfunds] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [investorfunds] SET ARITHABORT OFF 
GO
ALTER DATABASE [investorfunds] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [investorfunds] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [investorfunds] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [investorfunds] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [investorfunds] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [investorfunds] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [investorfunds] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [investorfunds] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [investorfunds] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [investorfunds] SET  DISABLE_BROKER 
GO
ALTER DATABASE [investorfunds] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [investorfunds] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [investorfunds] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [investorfunds] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [investorfunds] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [investorfunds] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [investorfunds] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [investorfunds] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [investorfunds] SET  MULTI_USER 
GO
ALTER DATABASE [investorfunds] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [investorfunds] SET DB_CHAINING OFF 
GO
ALTER DATABASE [investorfunds] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [investorfunds] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [investorfunds] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [investorfunds] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [investorfunds] SET QUERY_STORE = ON
GO
ALTER DATABASE [investorfunds] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [investorfunds]
GO
/****** Object:  Table [dbo].[Funds]    Script Date: 26-01-2025 23:58:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Funds](
	[FundId] [int] IDENTITY(1,1) NOT NULL,
	[FundName] [text] NOT NULL,
	[AmountInvested] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK__Funds__830DFC5A41460708] PRIMARY KEY CLUSTERED 
(
	[FundId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[InvestorFunds]    Script Date: 26-01-2025 23:58:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[InvestorFunds](
	[InvestorId] [int] NOT NULL,
	[FundId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[InvestorId] ASC,
	[FundId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Investors]    Script Date: 26-01-2025 23:58:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Investors](
	[InvestorId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [text] NOT NULL,
	[Email] [text] NOT NULL,
 CONSTRAINT [PK__Investor__41996EDE1FA8DDC9] PRIMARY KEY CLUSTERED 
(
	[InvestorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[InvestorFunds]  WITH CHECK ADD  CONSTRAINT [FK__InvestorF__FundI__3C69FB99] FOREIGN KEY([FundId])
REFERENCES [dbo].[Funds] ([FundId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[InvestorFunds] CHECK CONSTRAINT [FK__InvestorF__FundI__3C69FB99]
GO
ALTER TABLE [dbo].[InvestorFunds]  WITH CHECK ADD  CONSTRAINT [FK__InvestorF__Inves__3B75D760] FOREIGN KEY([InvestorId])
REFERENCES [dbo].[Investors] ([InvestorId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[InvestorFunds] CHECK CONSTRAINT [FK__InvestorF__Inves__3B75D760]
GO
USE [master]
GO
ALTER DATABASE [investorfunds] SET  READ_WRITE 
GO
